### ISSUE TITLE
8.0 create quotation from opportunity

### ISSUE THREAD

**Issue by lfreeke** [OCA/business-requirement#78]
When I'm in Opportunities and I click on the button 'Quotation from Business Requirements' I get the following error:  

Traceback (most recent call last):
  File "/.repo_requirements/odoo/openerp/http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/openerp/http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/openerp/http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/openerp/http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/openerp/http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/openerp/http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "/root/odoo-8.0/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/root/odoo-8.0/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/.repo_requirements/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/.repo_requirements/odoo/openerp/api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "/root/build/OCA/business-requirement/business_requirement_deliverable_crm/wizard/crm_make_sale.py", line 30, in make_orderline
    order_lines = self.prepare_sale_order_line(case_id, order_id)
  File "/root/build/OCA/business-requirement/business_requirement_deliverable_crm/wizard/crm_make_sale.py", line 43, in prepare_sale_order_line
    make sale order!"""))
TypeError: __init__() takes exactly 2 arguments (3 given)

**Comment by elicoidal** [comment]
@lfreeke Thanks for reporting.
We will have a look and report back to you
