### ISSUE TITLE
[8.0] Cannot duplicate the business requirement

### ISSUE THREAD

**Issue by elicoidal** [OCA/business-requirement#88]
When duplicating I get the following traceback:

Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]: 2017-03-21 04:05:18,710 249 ERROR elico_stable openerp.http: Exception during JSON request handling.
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]: Traceback (most recent call last):
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/http.py", line 544, in _handle_exception
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     return super(JsonRequest, self)._handle_exception(exception)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/http.py", line 581, in dispatch
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     result = self._call_function(**self.params)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/http.py", line 317, in _call_function
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     return checked_call(self.db, *args, **kwargs)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/service/model.py", line 118, in wrapper
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     return f(dbname, *args, **kwargs)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/http.py", line 314, in checked_call
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     return self.endpoint(*a, **kw)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/http.py", line 810, in __call__
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     return self.method(*args, **kw)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/http.py", line 410, in response_wrap
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     response = f(*args, **kw)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/addons/web/controllers/main.py", line 944, in call_kw
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     return self._call_kw(model, method, args, kwargs)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/addons/web/controllers/main.py", line 936, in _call_kw
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/api.py", line 268, in wrapper
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     return old_api(self, *args, **kwargs)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/models.py", line 4917, in copy
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     new_id = self.create(cr, uid, data, context)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/api.py", line 268, in wrapper
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     return old_api(self, *args, **kwargs)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/api.py", line 372, in old_api
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     result = method(recs, *args, **kwargs)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/additional_addons/business-requirement/business_requirement/models/business.py", line 190, in create
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     return super(BusinessRequirement, self).create(vals)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/api.py", line 266, in wrapper
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     return new_api(self, *args, **kwargs)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/api.py", line 508, in new_api
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     result = method(self._model, cr, uid, *args, **old_kwargs)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/addons/mail/mail_thread.py", line 381, in create
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/api.py", line 268, in wrapper
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     return old_api(self, *args, **kwargs)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/api.py", line 372, in old_api
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     result = method(recs, *args, **kwargs)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/additional_addons/connector/connector/producer.py", line 48, in create
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     record_id = create_original(self, vals)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/api.py", line 266, in wrapper
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     return new_api(self, *args, **kwargs)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/models.py", line 4126, in create
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     record = self.browse(self._create(old_vals))
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/api.py", line 266, in wrapper
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     return new_api(self, *args, **kwargs)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/api.py", line 508, in new_api
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     result = method(self._model, cr, uid, *args, **old_kwargs)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/models.py", line 4342, in _create
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     recs.recompute()
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/api.py", line 266, in wrapper
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     return new_api(self, *args, **kwargs)
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/models.py", line 5795, in recompute
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     name: rec[name] for name in names
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/models.py", line 5795, in <dictcomp>
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     name: rec[name] for name in names
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/models.py", line 5679, in __getitem__
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     return self._fields[key].__get__(self, type(self))
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/fields.py", line 841, in __get__
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     return record._cache[self]
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/models.py", line 6079, in __getitem__
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     return value.get() if isinstance(value, SpecialValue) else value
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:   File "/opt/odoo/sources/odoo/openerp/fields.py", line 56, in get
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]:     raise self.exception
Mar 21 12:05:18 superman docker/stable_odoo-elico_1[806]: AccessError: ('AccessError', u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: business.requirement, Operation: read)')

**Comment by elicoidal** [comment]
Fixed in current version of the modules
